### ISSUE TITLE
Could not load javascript 'src/build/main.js' for content script.

### ISSUE THREAD

**Issue by supritshah1289** [atakangktepe/react-parcel-extension-boilerplate#1]
Thank you for sharing a tutorial on Medium. I was not able to write a comment on medium for some reason. 

I cloned your project then I run build script. However, when I try to load it into chrome. I got an error 
Could not load javascript 'src/build/main.js' for content script.

**Comment by atakangktepe** [comment]
Are you sure to builded the project correctly? I ran "npm run build" then loaded it into chrome, that rendered correctly. I couldn't reproduce your issue.

**Comment by supritshah1289** [comment]
Sorry for late reply. Here is a pic of the error I was getting [error image](https://imgur.com/a/zKdfn)
Please look at the files in build folder and the command I ran in a terminal.

**Comment by atakangktepe** [comment]
Seems like it was builded successfully. Could you try to remove extension from chrome and re-install?

**Comment by supritshah1289** [comment]
Yes but my question is why did it build as main.js**.js**?

**Comment by supritshah1289** [comment]
In a build script at the end the command is declared to create output file with main.js. I already have file name main.js. That is why it ends up with **main.js.js** file name
